version: '3'

services:
  web:
    image: 'python:3.8'
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/pim_django
    working_dir: '/pim_django'
    ports:
      - '8000:8000'
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '33006:3306'
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_ROOT_PASSWORD: 'password'
