version: '3'

services:
  web:
    image: 'python:3.8'
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/pim_django
    working_dir: '/pim_django'
    ports:
      - '8000:8000'
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
      - elasticsearch
      - kibana

  db:
    image: mysql:5.7
    ports:
      - '33006:3306'
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_ROOT_PASSWORD: 'password'

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.1'
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms512m -Xmx512m}'
      discovery.type: 'single-node'
    ports:
      - 9210:9200
    depends_on:
      - db

  kibana:
#    mem_limit: 18874368000
    image: docker.elastic.co/kibana/kibana-oss:7.5.1
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
    ports:
      - 5603:5601
    depends_on:
      - elasticsearch
